name: gaang
on:
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' 
      - name: Installed package list
        run: apt list --installed
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.2.0  
      - name: Install all necessary packages
        run: pip install selenium-wire requests beautifulsoup4 pandas webdriver-manager selenium
      - name: Run the scraping script
        run: python gaang.py
